/* hooks.c

   Copyright (C) 2019-2016 Marcus Dansarie <marcus@dansarie.se>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program. If not, see <http://www.gnu.org/licenses/>. */

/* This file has been automatically generated by create-hooks. */

#include "../src/hooks.h"

#ifdef TESTING
Rtfun rtfun = {
  /* From stdio.h */
  .fprintf = fprintf,
  /* From stdlib.h */
  .malloc = malloc,
  .posix_memalign = posix_memalign,
  /* From time.h */
  .gmtime_r = gmtime_r,
  /* From openssl/evp.h */
  .EVP_DecodeBlock = EVP_DecodeBlock,
  .EVP_DigestSign = EVP_DigestSign,
  .EVP_DigestSignInit = EVP_DigestSignInit,
  .EVP_DigestVerify = EVP_DigestVerify,
  .EVP_DigestVerifyInit = EVP_DigestVerifyInit,
  .EVP_MD_CTX_new = EVP_MD_CTX_new,
  .EVP_MD_CTX_set_pkey_ctx = EVP_MD_CTX_set_pkey_ctx,
  .EVP_PKEY_CTX_new = EVP_PKEY_CTX_new,
  .EVP_PKEY_get_raw_public_key = EVP_PKEY_get_raw_public_key,
  .EVP_PKEY_new_raw_private_key = EVP_PKEY_new_raw_private_key,
  .EVP_PKEY_new_raw_public_key = EVP_PKEY_new_raw_public_key,
  /* From sys/socket.h */
  .sendmmsg = sendmmsg,
  /* From sys/timex.h */
  .ntp_adjtime = ntp_adjtime,
  /* From ../src/roughtime_common.h */
  .create_roughtime_message = create_roughtime_message,
  .get_header_tag = get_header_tag,
  .parse_roughtime_header = parse_roughtime_header,
  .sign = sign,
  .verify_signature = verify_signature,
  /* From ../src/roughtimed.h */
  .sha512_256 = sha512_256,
  .compute_merkle = compute_merkle,
  .add_queries = add_queries,
  .check_ver = check_ver
};
#endif /* TESTING */
