/* wrappers.h

   Copyright (C) 2019-2016 Marcus Dansarie <marcus@dansarie.se>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program. If not, see <http://www.gnu.org/licenses/>. */

/* This file has been automatically generated by create-hooks. */

#ifndef WRAPPERS_H
#define WRAPPERS_H

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#include "../src/roughtime_common.h"
#include <stdlib.h>
#include <time.h>
#include <openssl/evp.h>

void rtfun_reset(void);

/* From ../src/roughtime_common.h */

roughtime_result_t wrapped_get_header_tag(const roughtime_header_t *restrict header, uint32_t tag, uint32_t *restrict offset, uint32_t *restrict length);
void set_fail_get_header_tag(size_t start_call, size_t stop_call, roughtime_result_t return_value);
void set_val_get_header_tag_offset(uint32_t offset);
void set_val_get_header_tag_length(uint32_t length);
void reset_fail_get_header_tag(void);

roughtime_result_t wrapped_parse_roughtime_header(const uint8_t *restrict message, uint32_t message_len, roughtime_header_t *restrict header);
void set_fail_parse_roughtime_header(size_t start_call, size_t stop_call, roughtime_result_t return_value);
void set_val_parse_roughtime_header_header(roughtime_header_t header);
void reset_fail_parse_roughtime_header(void);

roughtime_result_t wrapped_verify_signature(const uint8_t *restrict data, uint32_t len, const uint8_t *restrict context, uint32_t context_len, const uint8_t *restrict signature, const uint8_t *restrict public_key);
void set_fail_verify_signature(size_t start_call, size_t stop_call, roughtime_result_t return_value);
void reset_fail_verify_signature(void);

/* From stdlib.h */

void * wrapped_malloc(size_t __size);
void set_fail_malloc(size_t start_call, size_t stop_call, void * return_value);
void reset_fail_malloc(void);

/* From time.h */

struct tm * wrapped_gmtime_r(const time_t *restrict __timer, struct tm *restrict __tp);
void set_fail_gmtime_r(size_t start_call, size_t stop_call, struct tm * return_value);
void set_val_gmtime_r___tp(struct tm __tp);
void reset_fail_gmtime_r(void);

/* From openssl/evp.h */

int wrapped_EVP_DecodeBlock(unsigned char * t, const unsigned char * f, int n);
void set_fail_EVP_DecodeBlock(size_t start_call, size_t stop_call, int return_value);
void set_val_EVP_DecodeBlock_t(unsigned char t);
void reset_fail_EVP_DecodeBlock(void);

int wrapped_EVP_DigestSign(EVP_MD_CTX * ctx, unsigned char * sigret, size_t * siglen, const unsigned char * tbs, size_t tbslen);
void set_fail_EVP_DigestSign(size_t start_call, size_t stop_call, int return_value);
void set_val_EVP_DigestSign_sigret(unsigned char sigret);
void set_val_EVP_DigestSign_siglen(size_t siglen);
void reset_fail_EVP_DigestSign(void);

int wrapped_EVP_DigestSignInit(EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey);
void set_fail_EVP_DigestSignInit(size_t start_call, size_t stop_call, int return_value);
void set_val_EVP_DigestSignInit_pctx(EVP_PKEY_CTX * pctx);
void reset_fail_EVP_DigestSignInit(void);

int wrapped_EVP_DigestVerify(EVP_MD_CTX * ctx, const unsigned char * sigret, size_t siglen, const unsigned char * tbs, size_t tbslen);
void set_fail_EVP_DigestVerify(size_t start_call, size_t stop_call, int return_value);
void reset_fail_EVP_DigestVerify(void);

int wrapped_EVP_DigestVerifyInit(EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey);
void set_fail_EVP_DigestVerifyInit(size_t start_call, size_t stop_call, int return_value);
void set_val_EVP_DigestVerifyInit_pctx(EVP_PKEY_CTX * pctx);
void reset_fail_EVP_DigestVerifyInit(void);

EVP_MD_CTX * wrapped_EVP_MD_CTX_new(void);
void set_fail_EVP_MD_CTX_new(size_t start_call, size_t stop_call, EVP_MD_CTX * return_value);
void reset_fail_EVP_MD_CTX_new(void);

void wrapped_EVP_MD_CTX_set_pkey_ctx(EVP_MD_CTX * ctx, EVP_PKEY_CTX * pctx);
void set_fail_EVP_MD_CTX_set_pkey_ctx(size_t start_call, size_t stop_call);
void reset_fail_EVP_MD_CTX_set_pkey_ctx(void);

EVP_PKEY_CTX * wrapped_EVP_PKEY_CTX_new(EVP_PKEY * pkey, ENGINE * e);
void set_fail_EVP_PKEY_CTX_new(size_t start_call, size_t stop_call, EVP_PKEY_CTX * return_value);
void reset_fail_EVP_PKEY_CTX_new(void);

int wrapped_EVP_PKEY_get_raw_public_key(const EVP_PKEY * pkey, unsigned char * pub, size_t * len);
void set_fail_EVP_PKEY_get_raw_public_key(size_t start_call, size_t stop_call, int return_value);
void set_val_EVP_PKEY_get_raw_public_key_pub(unsigned char pub);
void set_val_EVP_PKEY_get_raw_public_key_len(size_t len);
void reset_fail_EVP_PKEY_get_raw_public_key(void);

EVP_PKEY * wrapped_EVP_PKEY_new_raw_private_key(int type, ENGINE * e, const unsigned char * priv, size_t len);
void set_fail_EVP_PKEY_new_raw_private_key(size_t start_call, size_t stop_call, EVP_PKEY * return_value);
void reset_fail_EVP_PKEY_new_raw_private_key(void);

EVP_PKEY * wrapped_EVP_PKEY_new_raw_public_key(int type, ENGINE * e, const unsigned char * pub, size_t len);
void set_fail_EVP_PKEY_new_raw_public_key(size_t start_call, size_t stop_call, EVP_PKEY * return_value);
void reset_fail_EVP_PKEY_new_raw_public_key(void);

#endif /* WRAPPERS_H */
