/* wrappers.c

   Copyright (C) 2019-2016 Marcus Dansarie <marcus@dansarie.se>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program. If not, see <http://www.gnu.org/licenses/>. */

/* This file has been automatically generated by create-hooks. */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#include "wrappers.h"
#include "../src/hooks.h"

/* From ../src/roughtime_common.h */

size_t g_get_header_tag_call_counter = 0;
size_t g_get_header_tag_fail_start = 0;
size_t g_get_header_tag_fail_stop = 0;
bool g_get_header_tag_set_offset = false;
uint32_t g_get_header_tag_val_offset;
bool g_get_header_tag_set_length = false;
uint32_t g_get_header_tag_val_length;
roughtime_result_t g_get_header_tag_fail_val;
roughtime_result_t wrapped_get_header_tag(const roughtime_header_t *restrict header, uint32_t tag, uint32_t *restrict offset, uint32_t *restrict length) {
  g_get_header_tag_call_counter += 1;
  if (g_get_header_tag_fail_start > 0
      && g_get_header_tag_fail_start <= g_get_header_tag_call_counter
      && g_get_header_tag_fail_stop >= g_get_header_tag_call_counter) {
    if (g_get_header_tag_set_offset) {
      *offset = g_get_header_tag_val_offset;
    }
    if (g_get_header_tag_set_length) {
      *length = g_get_header_tag_val_length;
    }
    return g_get_header_tag_fail_val;
  }
  return get_header_tag(header, tag, offset, length);
}

void set_fail_get_header_tag(size_t start_call, size_t stop_call, roughtime_result_t return_value) {
  rtfun.get_header_tag = wrapped_get_header_tag;
  g_get_header_tag_call_counter = 0;
  g_get_header_tag_fail_start = start_call;
  g_get_header_tag_fail_stop = stop_call;
  g_get_header_tag_fail_val = return_value;
}

void set_val_get_header_tag_offset(uint32_t offset) {
  g_get_header_tag_set_offset = true;
  g_get_header_tag_val_offset = offset;
}

void set_val_get_header_tag_length(uint32_t length) {
  g_get_header_tag_set_length = true;
  g_get_header_tag_val_length = length;
}

void reset_fail_get_header_tag(void) {
  rtfun.get_header_tag = get_header_tag;
  g_get_header_tag_call_counter = 0;
  g_get_header_tag_fail_start = 0;
  g_get_header_tag_fail_stop = 0;
  g_get_header_tag_set_offset = false;
  g_get_header_tag_set_length = false;
}

size_t g_parse_roughtime_header_call_counter = 0;
size_t g_parse_roughtime_header_fail_start = 0;
size_t g_parse_roughtime_header_fail_stop = 0;
bool g_parse_roughtime_header_set_header = false;
roughtime_header_t g_parse_roughtime_header_val_header;
roughtime_result_t g_parse_roughtime_header_fail_val;
roughtime_result_t wrapped_parse_roughtime_header(const uint8_t *restrict message, uint32_t message_len, roughtime_header_t *restrict header) {
  g_parse_roughtime_header_call_counter += 1;
  if (g_parse_roughtime_header_fail_start > 0
      && g_parse_roughtime_header_fail_start <= g_parse_roughtime_header_call_counter
      && g_parse_roughtime_header_fail_stop >= g_parse_roughtime_header_call_counter) {
    if (g_parse_roughtime_header_set_header) {
      *header = g_parse_roughtime_header_val_header;
    }
    return g_parse_roughtime_header_fail_val;
  }
  return parse_roughtime_header(message, message_len, header);
}

void set_fail_parse_roughtime_header(size_t start_call, size_t stop_call, roughtime_result_t return_value) {
  rtfun.parse_roughtime_header = wrapped_parse_roughtime_header;
  g_parse_roughtime_header_call_counter = 0;
  g_parse_roughtime_header_fail_start = start_call;
  g_parse_roughtime_header_fail_stop = stop_call;
  g_parse_roughtime_header_fail_val = return_value;
}

void set_val_parse_roughtime_header_header(roughtime_header_t header) {
  g_parse_roughtime_header_set_header = true;
  g_parse_roughtime_header_val_header = header;
}

void reset_fail_parse_roughtime_header(void) {
  rtfun.parse_roughtime_header = parse_roughtime_header;
  g_parse_roughtime_header_call_counter = 0;
  g_parse_roughtime_header_fail_start = 0;
  g_parse_roughtime_header_fail_stop = 0;
  g_parse_roughtime_header_set_header = false;
}

size_t g_verify_signature_call_counter = 0;
size_t g_verify_signature_fail_start = 0;
size_t g_verify_signature_fail_stop = 0;
roughtime_result_t g_verify_signature_fail_val;
roughtime_result_t wrapped_verify_signature(const uint8_t *restrict data, uint32_t len, const uint8_t *restrict context, uint32_t context_len, const uint8_t *restrict signature, const uint8_t *restrict public_key) {
  g_verify_signature_call_counter += 1;
  if (g_verify_signature_fail_start > 0
      && g_verify_signature_fail_start <= g_verify_signature_call_counter
      && g_verify_signature_fail_stop >= g_verify_signature_call_counter) {
    return g_verify_signature_fail_val;
  }
  return verify_signature(data, len, context, context_len, signature, public_key);
}

void set_fail_verify_signature(size_t start_call, size_t stop_call, roughtime_result_t return_value) {
  rtfun.verify_signature = wrapped_verify_signature;
  g_verify_signature_call_counter = 0;
  g_verify_signature_fail_start = start_call;
  g_verify_signature_fail_stop = stop_call;
  g_verify_signature_fail_val = return_value;
}

void reset_fail_verify_signature(void) {
  rtfun.verify_signature = verify_signature;
  g_verify_signature_call_counter = 0;
  g_verify_signature_fail_start = 0;
  g_verify_signature_fail_stop = 0;
}
/* From stdlib.h */

size_t g_malloc_call_counter = 0;
size_t g_malloc_fail_start = 0;
size_t g_malloc_fail_stop = 0;
void * g_malloc_fail_val;
void * wrapped_malloc(size_t __size) {
  g_malloc_call_counter += 1;
  if (g_malloc_fail_start > 0
      && g_malloc_fail_start <= g_malloc_call_counter
      && g_malloc_fail_stop >= g_malloc_call_counter) {
    return g_malloc_fail_val;
  }
  return malloc(__size);
}

void set_fail_malloc(size_t start_call, size_t stop_call, void * return_value) {
  rtfun.malloc = wrapped_malloc;
  g_malloc_call_counter = 0;
  g_malloc_fail_start = start_call;
  g_malloc_fail_stop = stop_call;
  g_malloc_fail_val = return_value;
}

void reset_fail_malloc(void) {
  rtfun.malloc = malloc;
  g_malloc_call_counter = 0;
  g_malloc_fail_start = 0;
  g_malloc_fail_stop = 0;
}
/* From time.h */

size_t g_gmtime_r_call_counter = 0;
size_t g_gmtime_r_fail_start = 0;
size_t g_gmtime_r_fail_stop = 0;
bool g_gmtime_r_set___tp = false;
struct tm g_gmtime_r_val___tp;
struct tm * g_gmtime_r_fail_val;
struct tm * wrapped_gmtime_r(const time_t *restrict __timer, struct tm *restrict __tp) {
  g_gmtime_r_call_counter += 1;
  if (g_gmtime_r_fail_start > 0
      && g_gmtime_r_fail_start <= g_gmtime_r_call_counter
      && g_gmtime_r_fail_stop >= g_gmtime_r_call_counter) {
    if (g_gmtime_r_set___tp) {
      *__tp = g_gmtime_r_val___tp;
    }
    return g_gmtime_r_fail_val;
  }
  return gmtime_r(__timer, __tp);
}

void set_fail_gmtime_r(size_t start_call, size_t stop_call, struct tm * return_value) {
  rtfun.gmtime_r = wrapped_gmtime_r;
  g_gmtime_r_call_counter = 0;
  g_gmtime_r_fail_start = start_call;
  g_gmtime_r_fail_stop = stop_call;
  g_gmtime_r_fail_val = return_value;
}

void set_val_gmtime_r___tp(struct tm __tp) {
  g_gmtime_r_set___tp = true;
  g_gmtime_r_val___tp = __tp;
}

void reset_fail_gmtime_r(void) {
  rtfun.gmtime_r = gmtime_r;
  g_gmtime_r_call_counter = 0;
  g_gmtime_r_fail_start = 0;
  g_gmtime_r_fail_stop = 0;
  g_gmtime_r_set___tp = false;
}
/* From openssl/evp.h */

size_t g_EVP_DecodeBlock_call_counter = 0;
size_t g_EVP_DecodeBlock_fail_start = 0;
size_t g_EVP_DecodeBlock_fail_stop = 0;
bool g_EVP_DecodeBlock_set_t = false;
unsigned char g_EVP_DecodeBlock_val_t;
int g_EVP_DecodeBlock_fail_val;
int wrapped_EVP_DecodeBlock(unsigned char * t, const unsigned char * f, int n) {
  g_EVP_DecodeBlock_call_counter += 1;
  if (g_EVP_DecodeBlock_fail_start > 0
      && g_EVP_DecodeBlock_fail_start <= g_EVP_DecodeBlock_call_counter
      && g_EVP_DecodeBlock_fail_stop >= g_EVP_DecodeBlock_call_counter) {
    if (g_EVP_DecodeBlock_set_t) {
      *t = g_EVP_DecodeBlock_val_t;
    }
    return g_EVP_DecodeBlock_fail_val;
  }
  return EVP_DecodeBlock(t, f, n);
}

void set_fail_EVP_DecodeBlock(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_DecodeBlock = wrapped_EVP_DecodeBlock;
  g_EVP_DecodeBlock_call_counter = 0;
  g_EVP_DecodeBlock_fail_start = start_call;
  g_EVP_DecodeBlock_fail_stop = stop_call;
  g_EVP_DecodeBlock_fail_val = return_value;
}

void set_val_EVP_DecodeBlock_t(unsigned char t) {
  g_EVP_DecodeBlock_set_t = true;
  g_EVP_DecodeBlock_val_t = t;
}

void reset_fail_EVP_DecodeBlock(void) {
  rtfun.EVP_DecodeBlock = EVP_DecodeBlock;
  g_EVP_DecodeBlock_call_counter = 0;
  g_EVP_DecodeBlock_fail_start = 0;
  g_EVP_DecodeBlock_fail_stop = 0;
  g_EVP_DecodeBlock_set_t = false;
}

size_t g_EVP_DigestSign_call_counter = 0;
size_t g_EVP_DigestSign_fail_start = 0;
size_t g_EVP_DigestSign_fail_stop = 0;
bool g_EVP_DigestSign_set_sigret = false;
unsigned char g_EVP_DigestSign_val_sigret;
bool g_EVP_DigestSign_set_siglen = false;
size_t g_EVP_DigestSign_val_siglen;
int g_EVP_DigestSign_fail_val;
int wrapped_EVP_DigestSign(EVP_MD_CTX * ctx, unsigned char * sigret, size_t * siglen, const unsigned char * tbs, size_t tbslen) {
  g_EVP_DigestSign_call_counter += 1;
  if (g_EVP_DigestSign_fail_start > 0
      && g_EVP_DigestSign_fail_start <= g_EVP_DigestSign_call_counter
      && g_EVP_DigestSign_fail_stop >= g_EVP_DigestSign_call_counter) {
    if (g_EVP_DigestSign_set_sigret) {
      *sigret = g_EVP_DigestSign_val_sigret;
    }
    if (g_EVP_DigestSign_set_siglen) {
      *siglen = g_EVP_DigestSign_val_siglen;
    }
    return g_EVP_DigestSign_fail_val;
  }
  return EVP_DigestSign(ctx, sigret, siglen, tbs, tbslen);
}

void set_fail_EVP_DigestSign(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_DigestSign = wrapped_EVP_DigestSign;
  g_EVP_DigestSign_call_counter = 0;
  g_EVP_DigestSign_fail_start = start_call;
  g_EVP_DigestSign_fail_stop = stop_call;
  g_EVP_DigestSign_fail_val = return_value;
}

void set_val_EVP_DigestSign_sigret(unsigned char sigret) {
  g_EVP_DigestSign_set_sigret = true;
  g_EVP_DigestSign_val_sigret = sigret;
}

void set_val_EVP_DigestSign_siglen(size_t siglen) {
  g_EVP_DigestSign_set_siglen = true;
  g_EVP_DigestSign_val_siglen = siglen;
}

void reset_fail_EVP_DigestSign(void) {
  rtfun.EVP_DigestSign = EVP_DigestSign;
  g_EVP_DigestSign_call_counter = 0;
  g_EVP_DigestSign_fail_start = 0;
  g_EVP_DigestSign_fail_stop = 0;
  g_EVP_DigestSign_set_sigret = false;
  g_EVP_DigestSign_set_siglen = false;
}

size_t g_EVP_DigestSignInit_call_counter = 0;
size_t g_EVP_DigestSignInit_fail_start = 0;
size_t g_EVP_DigestSignInit_fail_stop = 0;
bool g_EVP_DigestSignInit_set_pctx = false;
EVP_PKEY_CTX * g_EVP_DigestSignInit_val_pctx;
int g_EVP_DigestSignInit_fail_val;
int wrapped_EVP_DigestSignInit(EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey) {
  g_EVP_DigestSignInit_call_counter += 1;
  if (g_EVP_DigestSignInit_fail_start > 0
      && g_EVP_DigestSignInit_fail_start <= g_EVP_DigestSignInit_call_counter
      && g_EVP_DigestSignInit_fail_stop >= g_EVP_DigestSignInit_call_counter) {
    if (g_EVP_DigestSignInit_set_pctx) {
      *pctx = g_EVP_DigestSignInit_val_pctx;
    }
    return g_EVP_DigestSignInit_fail_val;
  }
  return EVP_DigestSignInit(ctx, pctx, type, e, pkey);
}

void set_fail_EVP_DigestSignInit(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_DigestSignInit = wrapped_EVP_DigestSignInit;
  g_EVP_DigestSignInit_call_counter = 0;
  g_EVP_DigestSignInit_fail_start = start_call;
  g_EVP_DigestSignInit_fail_stop = stop_call;
  g_EVP_DigestSignInit_fail_val = return_value;
}

void set_val_EVP_DigestSignInit_pctx(EVP_PKEY_CTX * pctx) {
  g_EVP_DigestSignInit_set_pctx = true;
  g_EVP_DigestSignInit_val_pctx = pctx;
}

void reset_fail_EVP_DigestSignInit(void) {
  rtfun.EVP_DigestSignInit = EVP_DigestSignInit;
  g_EVP_DigestSignInit_call_counter = 0;
  g_EVP_DigestSignInit_fail_start = 0;
  g_EVP_DigestSignInit_fail_stop = 0;
  g_EVP_DigestSignInit_set_pctx = false;
}

size_t g_EVP_DigestVerify_call_counter = 0;
size_t g_EVP_DigestVerify_fail_start = 0;
size_t g_EVP_DigestVerify_fail_stop = 0;
int g_EVP_DigestVerify_fail_val;
int wrapped_EVP_DigestVerify(EVP_MD_CTX * ctx, const unsigned char * sigret, size_t siglen, const unsigned char * tbs, size_t tbslen) {
  g_EVP_DigestVerify_call_counter += 1;
  if (g_EVP_DigestVerify_fail_start > 0
      && g_EVP_DigestVerify_fail_start <= g_EVP_DigestVerify_call_counter
      && g_EVP_DigestVerify_fail_stop >= g_EVP_DigestVerify_call_counter) {
    return g_EVP_DigestVerify_fail_val;
  }
  return EVP_DigestVerify(ctx, sigret, siglen, tbs, tbslen);
}

void set_fail_EVP_DigestVerify(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_DigestVerify = wrapped_EVP_DigestVerify;
  g_EVP_DigestVerify_call_counter = 0;
  g_EVP_DigestVerify_fail_start = start_call;
  g_EVP_DigestVerify_fail_stop = stop_call;
  g_EVP_DigestVerify_fail_val = return_value;
}

void reset_fail_EVP_DigestVerify(void) {
  rtfun.EVP_DigestVerify = EVP_DigestVerify;
  g_EVP_DigestVerify_call_counter = 0;
  g_EVP_DigestVerify_fail_start = 0;
  g_EVP_DigestVerify_fail_stop = 0;
}

size_t g_EVP_DigestVerifyInit_call_counter = 0;
size_t g_EVP_DigestVerifyInit_fail_start = 0;
size_t g_EVP_DigestVerifyInit_fail_stop = 0;
bool g_EVP_DigestVerifyInit_set_pctx = false;
EVP_PKEY_CTX * g_EVP_DigestVerifyInit_val_pctx;
int g_EVP_DigestVerifyInit_fail_val;
int wrapped_EVP_DigestVerifyInit(EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey) {
  g_EVP_DigestVerifyInit_call_counter += 1;
  if (g_EVP_DigestVerifyInit_fail_start > 0
      && g_EVP_DigestVerifyInit_fail_start <= g_EVP_DigestVerifyInit_call_counter
      && g_EVP_DigestVerifyInit_fail_stop >= g_EVP_DigestVerifyInit_call_counter) {
    if (g_EVP_DigestVerifyInit_set_pctx) {
      *pctx = g_EVP_DigestVerifyInit_val_pctx;
    }
    return g_EVP_DigestVerifyInit_fail_val;
  }
  return EVP_DigestVerifyInit(ctx, pctx, type, e, pkey);
}

void set_fail_EVP_DigestVerifyInit(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_DigestVerifyInit = wrapped_EVP_DigestVerifyInit;
  g_EVP_DigestVerifyInit_call_counter = 0;
  g_EVP_DigestVerifyInit_fail_start = start_call;
  g_EVP_DigestVerifyInit_fail_stop = stop_call;
  g_EVP_DigestVerifyInit_fail_val = return_value;
}

void set_val_EVP_DigestVerifyInit_pctx(EVP_PKEY_CTX * pctx) {
  g_EVP_DigestVerifyInit_set_pctx = true;
  g_EVP_DigestVerifyInit_val_pctx = pctx;
}

void reset_fail_EVP_DigestVerifyInit(void) {
  rtfun.EVP_DigestVerifyInit = EVP_DigestVerifyInit;
  g_EVP_DigestVerifyInit_call_counter = 0;
  g_EVP_DigestVerifyInit_fail_start = 0;
  g_EVP_DigestVerifyInit_fail_stop = 0;
  g_EVP_DigestVerifyInit_set_pctx = false;
}

size_t g_EVP_MD_CTX_new_call_counter = 0;
size_t g_EVP_MD_CTX_new_fail_start = 0;
size_t g_EVP_MD_CTX_new_fail_stop = 0;
EVP_MD_CTX * g_EVP_MD_CTX_new_fail_val;
EVP_MD_CTX * wrapped_EVP_MD_CTX_new(void) {
  g_EVP_MD_CTX_new_call_counter += 1;
  if (g_EVP_MD_CTX_new_fail_start > 0
      && g_EVP_MD_CTX_new_fail_start <= g_EVP_MD_CTX_new_call_counter
      && g_EVP_MD_CTX_new_fail_stop >= g_EVP_MD_CTX_new_call_counter) {
    return g_EVP_MD_CTX_new_fail_val;
  }
  return EVP_MD_CTX_new();
}

void set_fail_EVP_MD_CTX_new(size_t start_call, size_t stop_call, EVP_MD_CTX * return_value) {
  rtfun.EVP_MD_CTX_new = wrapped_EVP_MD_CTX_new;
  g_EVP_MD_CTX_new_call_counter = 0;
  g_EVP_MD_CTX_new_fail_start = start_call;
  g_EVP_MD_CTX_new_fail_stop = stop_call;
  g_EVP_MD_CTX_new_fail_val = return_value;
}

void reset_fail_EVP_MD_CTX_new(void) {
  rtfun.EVP_MD_CTX_new = EVP_MD_CTX_new;
  g_EVP_MD_CTX_new_call_counter = 0;
  g_EVP_MD_CTX_new_fail_start = 0;
  g_EVP_MD_CTX_new_fail_stop = 0;
}

size_t g_EVP_MD_CTX_set_pkey_ctx_call_counter = 0;
size_t g_EVP_MD_CTX_set_pkey_ctx_fail_start = 0;
size_t g_EVP_MD_CTX_set_pkey_ctx_fail_stop = 0;
void wrapped_EVP_MD_CTX_set_pkey_ctx(EVP_MD_CTX * ctx, EVP_PKEY_CTX * pctx) {
  g_EVP_MD_CTX_set_pkey_ctx_call_counter += 1;
  if (g_EVP_MD_CTX_set_pkey_ctx_fail_start > 0
      && g_EVP_MD_CTX_set_pkey_ctx_fail_start <= g_EVP_MD_CTX_set_pkey_ctx_call_counter
      && g_EVP_MD_CTX_set_pkey_ctx_fail_stop >= g_EVP_MD_CTX_set_pkey_ctx_call_counter) {
    return;
  }
  EVP_MD_CTX_set_pkey_ctx(ctx, pctx);
}

void set_fail_EVP_MD_CTX_set_pkey_ctx(size_t start_call, size_t stop_call) {
  rtfun.EVP_MD_CTX_set_pkey_ctx = wrapped_EVP_MD_CTX_set_pkey_ctx;
  g_EVP_MD_CTX_set_pkey_ctx_call_counter = 0;
  g_EVP_MD_CTX_set_pkey_ctx_fail_start = start_call;
  g_EVP_MD_CTX_set_pkey_ctx_fail_stop = stop_call;
}

void reset_fail_EVP_MD_CTX_set_pkey_ctx(void) {
  rtfun.EVP_MD_CTX_set_pkey_ctx = EVP_MD_CTX_set_pkey_ctx;
  g_EVP_MD_CTX_set_pkey_ctx_call_counter = 0;
  g_EVP_MD_CTX_set_pkey_ctx_fail_start = 0;
  g_EVP_MD_CTX_set_pkey_ctx_fail_stop = 0;
}

size_t g_EVP_PKEY_CTX_new_call_counter = 0;
size_t g_EVP_PKEY_CTX_new_fail_start = 0;
size_t g_EVP_PKEY_CTX_new_fail_stop = 0;
EVP_PKEY_CTX * g_EVP_PKEY_CTX_new_fail_val;
EVP_PKEY_CTX * wrapped_EVP_PKEY_CTX_new(EVP_PKEY * pkey, ENGINE * e) {
  g_EVP_PKEY_CTX_new_call_counter += 1;
  if (g_EVP_PKEY_CTX_new_fail_start > 0
      && g_EVP_PKEY_CTX_new_fail_start <= g_EVP_PKEY_CTX_new_call_counter
      && g_EVP_PKEY_CTX_new_fail_stop >= g_EVP_PKEY_CTX_new_call_counter) {
    return g_EVP_PKEY_CTX_new_fail_val;
  }
  return EVP_PKEY_CTX_new(pkey, e);
}

void set_fail_EVP_PKEY_CTX_new(size_t start_call, size_t stop_call, EVP_PKEY_CTX * return_value) {
  rtfun.EVP_PKEY_CTX_new = wrapped_EVP_PKEY_CTX_new;
  g_EVP_PKEY_CTX_new_call_counter = 0;
  g_EVP_PKEY_CTX_new_fail_start = start_call;
  g_EVP_PKEY_CTX_new_fail_stop = stop_call;
  g_EVP_PKEY_CTX_new_fail_val = return_value;
}

void reset_fail_EVP_PKEY_CTX_new(void) {
  rtfun.EVP_PKEY_CTX_new = EVP_PKEY_CTX_new;
  g_EVP_PKEY_CTX_new_call_counter = 0;
  g_EVP_PKEY_CTX_new_fail_start = 0;
  g_EVP_PKEY_CTX_new_fail_stop = 0;
}

size_t g_EVP_PKEY_get_raw_public_key_call_counter = 0;
size_t g_EVP_PKEY_get_raw_public_key_fail_start = 0;
size_t g_EVP_PKEY_get_raw_public_key_fail_stop = 0;
bool g_EVP_PKEY_get_raw_public_key_set_pub = false;
unsigned char g_EVP_PKEY_get_raw_public_key_val_pub;
bool g_EVP_PKEY_get_raw_public_key_set_len = false;
size_t g_EVP_PKEY_get_raw_public_key_val_len;
int g_EVP_PKEY_get_raw_public_key_fail_val;
int wrapped_EVP_PKEY_get_raw_public_key(const EVP_PKEY * pkey, unsigned char * pub, size_t * len) {
  g_EVP_PKEY_get_raw_public_key_call_counter += 1;
  if (g_EVP_PKEY_get_raw_public_key_fail_start > 0
      && g_EVP_PKEY_get_raw_public_key_fail_start <= g_EVP_PKEY_get_raw_public_key_call_counter
      && g_EVP_PKEY_get_raw_public_key_fail_stop >= g_EVP_PKEY_get_raw_public_key_call_counter) {
    if (g_EVP_PKEY_get_raw_public_key_set_pub) {
      *pub = g_EVP_PKEY_get_raw_public_key_val_pub;
    }
    if (g_EVP_PKEY_get_raw_public_key_set_len) {
      *len = g_EVP_PKEY_get_raw_public_key_val_len;
    }
    return g_EVP_PKEY_get_raw_public_key_fail_val;
  }
  return EVP_PKEY_get_raw_public_key(pkey, pub, len);
}

void set_fail_EVP_PKEY_get_raw_public_key(size_t start_call, size_t stop_call, int return_value) {
  rtfun.EVP_PKEY_get_raw_public_key = wrapped_EVP_PKEY_get_raw_public_key;
  g_EVP_PKEY_get_raw_public_key_call_counter = 0;
  g_EVP_PKEY_get_raw_public_key_fail_start = start_call;
  g_EVP_PKEY_get_raw_public_key_fail_stop = stop_call;
  g_EVP_PKEY_get_raw_public_key_fail_val = return_value;
}

void set_val_EVP_PKEY_get_raw_public_key_pub(unsigned char pub) {
  g_EVP_PKEY_get_raw_public_key_set_pub = true;
  g_EVP_PKEY_get_raw_public_key_val_pub = pub;
}

void set_val_EVP_PKEY_get_raw_public_key_len(size_t len) {
  g_EVP_PKEY_get_raw_public_key_set_len = true;
  g_EVP_PKEY_get_raw_public_key_val_len = len;
}

void reset_fail_EVP_PKEY_get_raw_public_key(void) {
  rtfun.EVP_PKEY_get_raw_public_key = EVP_PKEY_get_raw_public_key;
  g_EVP_PKEY_get_raw_public_key_call_counter = 0;
  g_EVP_PKEY_get_raw_public_key_fail_start = 0;
  g_EVP_PKEY_get_raw_public_key_fail_stop = 0;
  g_EVP_PKEY_get_raw_public_key_set_pub = false;
  g_EVP_PKEY_get_raw_public_key_set_len = false;
}

size_t g_EVP_PKEY_new_raw_private_key_call_counter = 0;
size_t g_EVP_PKEY_new_raw_private_key_fail_start = 0;
size_t g_EVP_PKEY_new_raw_private_key_fail_stop = 0;
EVP_PKEY * g_EVP_PKEY_new_raw_private_key_fail_val;
EVP_PKEY * wrapped_EVP_PKEY_new_raw_private_key(int type, ENGINE * e, const unsigned char * priv, size_t len) {
  g_EVP_PKEY_new_raw_private_key_call_counter += 1;
  if (g_EVP_PKEY_new_raw_private_key_fail_start > 0
      && g_EVP_PKEY_new_raw_private_key_fail_start <= g_EVP_PKEY_new_raw_private_key_call_counter
      && g_EVP_PKEY_new_raw_private_key_fail_stop >= g_EVP_PKEY_new_raw_private_key_call_counter) {
    return g_EVP_PKEY_new_raw_private_key_fail_val;
  }
  return EVP_PKEY_new_raw_private_key(type, e, priv, len);
}

void set_fail_EVP_PKEY_new_raw_private_key(size_t start_call, size_t stop_call, EVP_PKEY * return_value) {
  rtfun.EVP_PKEY_new_raw_private_key = wrapped_EVP_PKEY_new_raw_private_key;
  g_EVP_PKEY_new_raw_private_key_call_counter = 0;
  g_EVP_PKEY_new_raw_private_key_fail_start = start_call;
  g_EVP_PKEY_new_raw_private_key_fail_stop = stop_call;
  g_EVP_PKEY_new_raw_private_key_fail_val = return_value;
}

void reset_fail_EVP_PKEY_new_raw_private_key(void) {
  rtfun.EVP_PKEY_new_raw_private_key = EVP_PKEY_new_raw_private_key;
  g_EVP_PKEY_new_raw_private_key_call_counter = 0;
  g_EVP_PKEY_new_raw_private_key_fail_start = 0;
  g_EVP_PKEY_new_raw_private_key_fail_stop = 0;
}

size_t g_EVP_PKEY_new_raw_public_key_call_counter = 0;
size_t g_EVP_PKEY_new_raw_public_key_fail_start = 0;
size_t g_EVP_PKEY_new_raw_public_key_fail_stop = 0;
EVP_PKEY * g_EVP_PKEY_new_raw_public_key_fail_val;
EVP_PKEY * wrapped_EVP_PKEY_new_raw_public_key(int type, ENGINE * e, const unsigned char * pub, size_t len) {
  g_EVP_PKEY_new_raw_public_key_call_counter += 1;
  if (g_EVP_PKEY_new_raw_public_key_fail_start > 0
      && g_EVP_PKEY_new_raw_public_key_fail_start <= g_EVP_PKEY_new_raw_public_key_call_counter
      && g_EVP_PKEY_new_raw_public_key_fail_stop >= g_EVP_PKEY_new_raw_public_key_call_counter) {
    return g_EVP_PKEY_new_raw_public_key_fail_val;
  }
  return EVP_PKEY_new_raw_public_key(type, e, pub, len);
}

void set_fail_EVP_PKEY_new_raw_public_key(size_t start_call, size_t stop_call, EVP_PKEY * return_value) {
  rtfun.EVP_PKEY_new_raw_public_key = wrapped_EVP_PKEY_new_raw_public_key;
  g_EVP_PKEY_new_raw_public_key_call_counter = 0;
  g_EVP_PKEY_new_raw_public_key_fail_start = start_call;
  g_EVP_PKEY_new_raw_public_key_fail_stop = stop_call;
  g_EVP_PKEY_new_raw_public_key_fail_val = return_value;
}

void reset_fail_EVP_PKEY_new_raw_public_key(void) {
  rtfun.EVP_PKEY_new_raw_public_key = EVP_PKEY_new_raw_public_key;
  g_EVP_PKEY_new_raw_public_key_call_counter = 0;
  g_EVP_PKEY_new_raw_public_key_fail_start = 0;
  g_EVP_PKEY_new_raw_public_key_fail_stop = 0;
}

void rtfun_reset(void) {
  reset_fail_get_header_tag();
  reset_fail_parse_roughtime_header();
  reset_fail_verify_signature();
  reset_fail_malloc();
  reset_fail_gmtime_r();
  reset_fail_EVP_DecodeBlock();
  reset_fail_EVP_DigestSign();
  reset_fail_EVP_DigestSignInit();
  reset_fail_EVP_DigestVerify();
  reset_fail_EVP_DigestVerifyInit();
  reset_fail_EVP_MD_CTX_new();
  reset_fail_EVP_MD_CTX_set_pkey_ctx();
  reset_fail_EVP_PKEY_CTX_new();
  reset_fail_EVP_PKEY_get_raw_public_key();
  reset_fail_EVP_PKEY_new_raw_private_key();
  reset_fail_EVP_PKEY_new_raw_public_key();
}
